Rbsfxirjtp 246
banica-org/dojo pull request #30
Opened 2021-04-23 14:10 UTC by emarinova

Implement Docker Notifications in Notifications Service
Notify Senesei if build has failed

2021-04-28 11:44 UTC, SlavinaKlisarska requested changes

2021-04-28 11:44 UTC, SlavinaKlisarska commented on notifications/src/main/java/com/dojo/notifications/service/messageGenerator/mail/TestResultsMailMessageGenerator.java
> +        return getTemplateEngine().process("testResultsMailTemplate", context);
extract constant

2021-04-28 13:46 UTC, emarinova commented on messages/src/main/proto/userdetails.proto
> +  rpc getUserDetailsById(ByIdRequest) returns (UserDetailsResponse);
It doesn't accept rpc-s with the same name even with different parameters
![image](https://user-images.githubusercontent.com/32341708/116414510-33c7ba00-a841-11eb-9ff9-cfaa5f4a4031.png)

2021-04-29 11:29 UTC, SlavinaKlisarska approved these changes

2021-04-29 11:33 UTC, merged